### ISSUE TITLE
Cache/use base directory instead of root

### ISSUE THREAD

**Issue by raucao** [rchrd2/hello-remotestorage#1]
Love this example! Nice work.

Just one thing I'd propose to change: currently it's caching/using the root of a storage, meaning when someone connects their storage, it will cache every single document they have already stored (and also show all base directories of it in the list). I'd suggest to change it to something like "react-demo" or just "demo" at least, so that it only caches and writes the files from the demo (or other demos), and also only shows demo files in the listing.

**Comment by rchrd2** [comment]
Good idea. I'll do that soon.
