### ISSUE TITLE
Disconnect account

### ISSUE THREAD

**Issue by raucao** [rchrd2/hello-remotestorage#2]
I played around a bit more with the demo and found that there's no way disconnect the account. However, when one is already connected it's still possible to click the connect button and fill in the form, but without the app reacting (because it's still connected).

How about turning the connect button into a working disconnect button when an account is being connected? This way, it would be a complete demo for the whole flow, which you'd usually want to add to an app, and it would also fix the connect button not working anymore once an account is connected, until you manually clear your localStorage.

**Comment by rchrd2** [comment]
Thanks for the feedback. I just pushed an update which adds the disconnect feature. 

I also added an file upload example.

**Comment by raucao** [comment]
Great!
